`error.js`파일 컨벤션은 next routes내에서의 예측 못한 runtime error를 처리할 수 있게 한다.

- 자동으로 route segment와 nested children을  [React Error Boundary](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary)로 wrap한다.
- 세분성을 조절하기 위해서 특정 segment를 위한 맞춤형 error Ui를 파일-시스템 계층을 통하여 만든다
- 에러의 영향을 받는 segment를 나머지 application부분에서 고립시킨다.
- 페이지 전체 새로고침을 하지 않고 해당 에러를 잡는 기능을 더할 수 있다.
`error.js`파일을 route segment에 더하고 react component를 exporting 하여 errorUI를 만든다.
![[error-special-file.avif]]
app/dashboard/error.tsx
```typescript
'use client' // Error components must be Client Components
 
import { useEffect } from 'react'
 
export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  useEffect(() => {
    // Log the error to an error reporting service
    console.error(error)
  }, [error])
 
  return (
    <div>
      <h2>Something went wrong!</h2>
      <button
        onClick={
          // Attempt to recover by trying to re-render the segment
          () => reset()
        }
      >
        Try again
      </button>
    </div>
  )
}
```
## `error.js`의 작동방식![[error-overview.avif]]
- `error.js`는 자동으로 [React Error Boundary](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary)를 만든다. 이건 nested child segment나 `page.js` 컴포넌트를 wrap한다
- `error.js`에서 export된 리액트 컴포넌트파일은 fallback 컴포넌트로 사용된다.
- 만약 에러 영역 내에서 에러가 (thrown)일어난다면, 에러는 (contained)보관되고, fallback component가 렌더된다
- fallback 에러 컴포넌트가 활성화돼있을때 error 바운더리의 상위 layout들은 본인들의 state를 유지하고 상호작용 가능하게 유지된다. 그리고 에러 컴포넌트가 에러를 해결해주는 동작을 할 수 있다.
## Recovering from errors
가끔 에러는 일시적인 것이라 기능을 다시 작동시키는것만으로도 해결이 된다.

에러 컴포넌트는 `reset()` 함수를 써서 에러 범위 내의 컨텐츠를 re-rendering하게 할 수 있다.
성공적이면 fallback error 컴포넌트는 새로 렌더링 된 컨텐츠를
app/dashboard/error.tsx
```typescript
'use client'
 
export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  return (
    <div>
      <h2>Something went wrong!</h2>
      <button onClick={() => reset()}>Try again</button>
    </div>
  )
}
```

## Nested Routes
[special files](0. Next.js project structure) 에 의하여 생성된 리액트 컴포넌트들은 특정 중첩(nested) 계급도에 의하여 렌더링된다
![[Pasted image 20240123011113.png]]
예를 들자면, `layout.js` 과 `error.js` 를 포함하는 2개의 segment를 가진 중첩 route는 아래 사진의 컴포넌트 계층에 따라 렌더링된다.
![[nested-error-component-hierarchy.avif]]
중첩 컴포넌트 계층은 중첩 route에 있는 `error.js`의 작동방식에 어느정도 영향력을 행사한다
-  에러는 가장 가까운 parent 에러 범위까지 차오른다(bubble up). `error.js` 파일은 모든 하위 중첩 child segment들의 에러도 처리하려고 한다는 의미다. 각 폴더 경로에 `error.js` 파일을 추가하여 편집해준다면 이런 동작을 조금 세분화시켜줄 수 있다.
- ***`error.js` boundary는  같은 세그먼트 내에 존재하는 `layout.js`의 컴포넌트에서 일어난 에러는 처리하지 않음. 왜냐면 계층상으로 하위에 존재해서 그렇다. 하위 segment의 `layout.js`의 에러에는 영향을 끼칠 수 있다***
## Handling errors in Layouts
- `error.js` 바운더리는 같은 segment 내의 `layout.js`나 `template.js`의 에러를 catch하지 않음.
- 그래서 layout이나 template의 에러를 잡기 위해서는 그냥 그 상위 세그먼트에 `error.js`만들면 됨.
- root세그먼트에 있는 layout이나 template의 에러를 잡고 싶으면 더 상위 세그먼트를 만들수 없으니  `global-error.js`를 사용한다.
- `global-error.js` 는 그냥  애플리케이션 전체를 감싸버림. catch-all 이라고 생각하면 편하다.
- root 세그먼트에서 에러가 났을때 `global-error.js` 의 해당 fallback이 애플리케이션 전체를 대체 해버리다 보니,  자체적인 `html`과 `body` 태그를 보유하고 있어야 한다.
- 웬만해서  작동할 일이 없긴 하다. 하위 세그먼트의 `error.js`에서 다 해결해주다 보니
- `global-error.js` 잘 정의 돼있어도 root segment의  `error.js`를 쓰는 것을 권장한다.
app/global-error.tsx
```typescript
'use client'
 
export default function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  return (
    <html>
      <body>
        <h2>Something went wrong!</h2>
        <button onClick={() => reset()}>Try again</button>
      </body>
    </html>
  )
}
```

## Handling Server Errors
- 서버 컴포넌트 내에서 에러가 발생한다면 next,js 는 `error` 객체를 `error` prop에서 가장 가까운 `error.js`로 전달(forwarding) 한다.
### Securing Sensitive Error Information
- 클라이언트에게 전달된`error` rorcpsms 제네릭 `message`와`digest`property만을 가지고 있다고 한다.
- 이 방법을 사용하는 이유는 민감한 개인정보 등을 유출하지 않기 위해서 이다.
- `message`는 에러에 대한 제네릭 메세지를 포함하고
- `digest` 서버사이드 에러 로그와 대조할 수 있도록 에러에 대한 해시를 자동생성해서 가지고 있다.
- 개발동안  클라이언트에게 전달된 `Error` 객체는 디버깅을 쉽게 하기 위해serialized된 후 오리지널 에러의 `message`를 포함하게 된다.
